### ISSUE TITLE
Novos middlewares

### ISSUE THREAD

**Issue by netopvh** [jetimob/http-php-laravel#4]
E ai pessoal, achei bem bacana esse package e gostaria de saber se posso inserir novos middlewares para integrar em um package que estou fazendo para api do Asaas.

Ele usa um access token, não tem encode64.

**Comment by alanwgt** [comment]
Olá, @netopvh!

É possível sim adicionar middlewares à *stack* do Guzzle.

Tu pode tomar [este projeto da Juno](https://github.com/jetimob/juno-sdk-php-laravel/tree/v2) como exemplo. Dentro do arquivo de configurações desse projeto, o caminho `http.guzzle.middlewares` utiliza o *middleware* ` \Jetimob\Http\Middlewares\OAuthRequestMiddleware::class` que adiciona as credenciais necessários às requisições. Creio que tu pode utilizar esse middlware como base para atender as tuas necessidades.

Abraço!
